version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - ./api:/var/www
    depends_on:
      - mysql
    networks:
      - ucl_simulator

  react:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: react-app
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3010:3000"
    command: sh -c "npm install && npm start"
    networks:
      - ucl_simulator

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - ucl_simulator

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ucl_simulator_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel_password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ucl_simulator

volumes:
  mysql-data:

networks:
  ucl_simulator:
    driver: bridge
